---
title: "Heatmap"
author: Henry Paz and Vanessa De La Guardia
output: html_document
---

Heat tree for differentially abundant ASV's in the rumen 
```{r}
library(tidyverse)
library(data.table)
library(Heatplus)
library(vegan) 
library(gplots) 

#generate ASV table
rumen_table <-  read_tsv("exported/table_rarefied_rumen/feature-table.txt", skip=1) %>%
  rename(OTUID="#OTU ID") 

#transform to proportions
rumen_table_df <- as.data.frame(rumen_table) 
rownames(rumen_table_df) <- rumen_table_df[,1]
rumen_table_df <- rumen_table_df[,-1]
rumen_table_df_t <- t(rumen_table_df)
rumen_table_prop <- rumen_table_df_t/rowSums(rumen_table_df_t)

#format 
rumen_table_prop_t <- t(rumen_table_prop)
rumen_table_prop_t <- as.data.frame(rumen_table_prop_t)
rumen_table_prop_t <- setDT(rumen_table_prop_t, keep.rownames=T)[] 
names(rumen_table_prop_t)[1] <- "OTUID" 

############################################################################################
#list unique ASV 
rumen_list <-  read_tsv("heatmap/rumen_taxa.txt")

#join rumen_list and rumen_table_prop_t tbl
rumen_tax_data <- left_join(rumen_list, rumen_table_prop_t, by=c("X1"="OTUID"))
rumen_tax_data$unique <- gsub("__", "_", rumen_tax_data$unique)


#format
rumen_prop <- rumen_tax_data %>% 
  select(-X1) %>% 
  select(unique, everything()) 

rumen_prop_t <- as.data.frame(t(rumen_prop), stringsAsFactors=F)
colnames(rumen_prop_t) <- as.character(unlist(rumen_prop_t[1,]))
rumen_prop_t <- rumen_prop_t[-1,]
col.nums <- c(1:76)
rumen_prop_t[col.nums] <- sapply(rumen_prop_t[col.nums],as.numeric)
names(rumen_prop_t) <- make.unique(names(rumen_prop_t), sep = ".")

#Heatmap formating
#set color and dendogram
scaleblackblue <- colorRampPalette(c("white", "#800000"), space = "rgb")(100)
data.dist <- vegdist(rumen_prop_t, method = "bray")
row.clus <- hclust(data.dist, "aver")
data.dist.g <- vegdist(t(rumen_prop_t), method = "bray")
col.clus <- hclust(data.dist.g, "aver")

############################################################################################
metadata <- read_tsv("metadata/metadata.txt") %>% 
  rename(OTUID="#SampleID") %>% 
  slice(2:24) %>% 
  na.omit() 

metadata <- metadata %>% 
  mutate(var = if_else(Phenotype == "High Neff", "blue", "red"))

rumen_sample_list <-  colnames(rumen_table_prop_t)              
rumen_sample_list_df <- as.data.frame(rumen_sample_list)
rumen_sample_list_df <- as.data.frame(rumen_sample_list_df[-1,])
names(rumen_sample_list_df)[1] <- "OTUID"

#join 
rumen_var_data <- left_join(rumen_sample_list_df, metadata, by = "OTUID") %>% 
  select(OTUID, var)

#join rumen_prop_t and rumen_var_data
rumen_var_data_df <- as.data.frame(rumen_var_data)
rownames(rumen_var_data_df) <- rumen_var_data_df [,1]
rumen_var_data_df <- rumen_var_data_df[,-1]
cbind(row.names(rumen_prop_t), rumen_var_data_df)

#generate heatmap
pdf("heatmap/heatmap_rumen.pdf", height=6, width=10)
heatmap.2(as.matrix(rumen_prop_t), Rowv=as.dendrogram(row.clus), Colv=as.dendrogram(col.clus), xlab="Amplicon Sequence Variants", ylab="Samples", col=scaleblackblue, RowSideColors= rumen_var_data_df, trace="none", density.info="none", margins=c(17,5), lhei = c(2, 6))
dev.off()
```

Heat tree for differentially abundant ASV's in the feces 
```{r}
library(tidyverse)
library(data.table)
library(Heatplus)
library(vegan) 
library(gplots) 

#generate ASV table
feces_table <-  read_tsv("exported/table_rarefied_feces/feature-table.txt", skip=1) %>%
  rename(OTUID="#OTU ID") 

#transform to proportions
feces_table_df <- as.data.frame(feces_table) 
rownames(feces_table_df) <- feces_table_df[,1]
feces_table_df <- feces_table_df[,-1]
feces_table_df_t <- t(feces_table_df)
feces_table_prop <- feces_table_df_t/rowSums(feces_table_df_t)

#format 
feces_table_prop_t <- t(feces_table_prop)
feces_table_prop_t <- as.data.frame(feces_table_prop_t)
feces_table_prop_t <- setDT(feces_table_prop_t, keep.rownames=T)[] #set rownames as 1st column
names(feces_table_prop_t)[1] <- "OTUID" #rename first column

############################################################################################
#list unique ASV 
feces_list <-  read_tsv("heatmap/feces_taxa.txt")

#join feces_list and feces_table_prop_t tbl
feces_tax_data <- left_join(feces_list, feces_table_prop_t, by=c("X1"="OTUID"))
feces_tax_data$unique <- gsub("__", "_", feces_tax_data$unique)


#format
feces_prop <- feces_tax_data %>% 
  select(-X1) %>% 
  select(unique, everything()) #reorder columns

feces_prop_t <- as.data.frame(t(feces_prop), stringsAsFactors=F)
colnames(feces_prop_t) <- as.character(unlist(feces_prop_t[1,])) 
feces_prop_t <- feces_prop_t[-1,]
col.nums <- c(1:35)
feces_prop_t[col.nums] <- sapply(feces_prop_t[col.nums],as.numeric)
names(feces_prop_t) <- make.unique(names(feces_prop_t), sep = ".")

#Heatmap formating
#color and dendograms
scaleblackblue <- colorRampPalette(c("white", "#800000"), space = "rgb")(100)
data.dist <- vegdist(feces_prop_t, method = "bray")
row.clus <- hclust(data.dist, "aver")
data.dist.g <- vegdist(t(feces_prop_t), method = "bray")
col.clus <- hclust(data.dist.g, "aver")

############################################################################################
metadata <- read_tsv("metadata/metadata.txt") %>% 
  rename(OTUID="#SampleID") %>% 
  slice(2:24) %>% 
  na.omit() 

metadata <- metadata %>% 
  mutate(var = if_else(Phenotype == "High Neff", "blue", "red"))

feces_sample_list <-  colnames(feces_table_prop_t)              
feces_sample_list_df <- as.data.frame(feces_sample_list)
feces_sample_list_df <- as.data.frame(feces_sample_list_df[-1,])
names(feces_sample_list_df)[1] <- "OTUID"

#join 
feces_var_data <- left_join(feces_sample_list_df, metadata, by = "OTUID") %>% 
  select(OTUID, var)

#join feces_prop_t and feces_var_data
feces_var_data_df <- as.data.frame(feces_var_data)
rownames(feces_var_data_df) <- feces_var_data_df [,1]
feces_var_data_df <- feces_var_data_df[,-1]
cbind(row.names(feces_prop_t), feces_var_data_df)

#generate heatmap
pdf("heatmap/heatmap_feces.pdf", height=5, width=6)
heatmap.2(as.matrix(feces_prop_t), Rowv=as.dendrogram(row.clus), Colv=as.dendrogram(col.clus), xlab="Genus Rank", ylab="Samples", col=scaleblackblue, RowSideColors= feces_var_data_df, trace="none", density.info="none", margins=c(17,5), lhei = c(2, 6))
dev.off()
```

